FROM: tensorflow/tensorflow:latest-gpu-py3

RUN apt-get update && apt-get upgrade -y

RUN pip install pip -U
RUN pip install numpy
RUN pip install matplotlib
RUN pip install pandas
RUN pip install scikit-learn
RUN pip install cloudmesh-common
RUN pip install cloudmesh-gpu
